import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import "./styles/reset.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Takumi Okayasu's portfolio",
  description: "Generated by create next app",
};

function Header() {
  return <header></header>;
}

function Footer() {
  return <footer></footer>;
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <Header />
      <body className={inter.className}>{children}</body>
      <Footer />
    </html>
  );
}
