import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/reset.css";

export const metadata: Metadata = {
  title: "Takumi Okayasu's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
